[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde={workspace = true, features = ["derive"]}
sqlx={ workspace = true, features = ["runtime-async-std", "postgres", "uuid", "chrono"], optional = true }



[features]
ssr=["dep:sqlx"]