[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
sqlx = { version = "0.8.5", features = ["runtime-async-std", "postgres", "uuid", "chrono"], optional = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
thiserror = { workspace = true }

tokio = {workspace=true, optional = true, features = ["process"]}

[features]
website-ssr = ["dep:sqlx"]
website-to-server=[]
website-to-hosting=[]
server=["tokio"]
